### PR TITLE
Garden GC changes may require actions from operators

### PR DESCRIPTION
**Pull request by mrosecrance**
- details where they can go for more information

Only relevant for PAS 2.4 onwards.

Co-authored-by: Claudia Beresford <cberesford@pivotal.io>

### CODE REVIEW

**Comment by pspinrad** [comment]
Thanks @mrosecrance quick questions- you say:

> If you've set your **Application Container** -> **Docker Images Disk-Cleanup Scheduling on Cell VMs** to default, routine or never there is no action that needs to be taken

By "default" you mean, you select **Clean up disk-space once threshold is reached** AND change the threshold value in the field below, right?  Because just selecting never, routinely, or threshold are the only three options-- so I'm guessing no action is needed if you choose any of those, if you don't also change the field below.  I'm looking at https://docs.pivotal.io/pivotalcf/2-4/customizing/gcp-er-config.html#application-containers-config (login: pivotalcf / wilderror16)

**Comment by pspinrad** [comment]
@mrosecrance nev mind-- assuming yes re ^, will merge now...

**Comment by mrosecrance** [comment]
You've got it exactly but maybe it should be clearer. It was meant to indicate that if the operator never touched this field it would be "defaulted" to threshold with a set value. If the value wasn't changed, we don't force an operator action. If they did change the threshold value, we assume they know what they're doing and force them to pick a value on upgrade.

**Comment by pspinrad** [comment]
@mrosecrance good to know-- a couple more q's:

1. Is the default value for 2.3 always gonna be`10240`?  I put that number in the text, would like to be that specific if it's always true, but not sure if it is.

2.  If the threshold was changed (in 2.3 install) when are operators forced to pick a new value?  Like, is there some validation check on the 2.4 config form field that prevents deploy if you leave the field blank?

3. How does the threshold work differently in 2.4 vs 2.3?  Is it that in 2.3 cleanup triggers when disk use _exceeds_ the threshold, while in 2.4, disk cleanup triggers when _unused_ disk space _falls below_ the threshold?

Thanks again--

**Comment by mrosecrance** [comment]
@pspinrad 
1. The default for threshold in 2.3 and previous should be 10240. We will migrate that to a reserved value of 15360.

2. We tested it manually and the tile show's as not complete without a value selected. I think that's just Opsman behavior.

3. Your threshold assumption is correct. In 2.4 disk cleanup will trigger when we hit All available disk - reserved amount. The reserved amount is space for the diego cache and packages.

**Comment by pspinrad** [comment]
Thanks again @mrosecrance !

**Pull request merged**
