### PR TITLE
Add nfs-legacy volume service migration steps

### PR DESCRIPTION
**Pull request by paulcwarren**
[#168965468](https://www.pivotaltracker.com/story/show/168965468)

cc/ @julian-hj @DennisDenuto

### CODE REVIEW

**Comment by mlimonczenko** [comment]
Thank you, @paulcwarren

**Comment by mlimonczenko** [comment]
@paulcwarren (@julian-hj @DennisDenuto). I did a fairly large revision for formatting. Feel free to review in case I misconstrued any meaning. Because this seems important, I will be bringing this to production shortly.

**Comment by julian-hj** [comment]
It's probably unrelated to your reformat, but I see a couple minor issues in this paragraph:

> 3. Find if there are apps that need to be manually updated to be compatible with v2.7. If you are running a small footprint PAS, substitute `diego-cell` in the command.

Could we change it to:

> 3. Determine whether there are apps that need to be manually updated to be compatible with v2.6. (Note: If you are running a small footprint PAS, replace `diego-cell` with `compute` in the command.)

**Comment by mlimonczenko** [comment]
Yes. I can make those changes right now. It looks like I did misunderstand that line in step 3, since `diego-cell` and `compute` were not in tick marks, and I thought "compute" was a verb.

**Comment by mlimonczenko** [comment]
Thank you very much for taking a look!

**Pull request merged**
